### ISSUE TITLE
Incompatible with TestMod, always crash

### ISSUE THREAD

**Issue by 280chan** [Jerry-Licious/force-key#2]
workshop link for TestMod: https://steamcommunity.com/sharedfiles/filedetails/?id=1614158341
btw I'm the Author of TestMod, but can't find out the reason of the crash, can also connect me on discord at 280chan#0001
crash log when opening map after gaining bless of Neow:
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.VerifyError: Illegal type at constant pool entry 102 in class forcekey.OverrideConnectionPatch
Exception Details:
  Location:
    forcekey/OverrideConnectionPatch.overrideConnection(Lcom/megacrit/cardcrawl/map/MapRoomNode;[Ljava/lang/Boolean;[Ljava/lang/Boolean;)V @58: invokestatic
  Reason:
    Constant pool index 102 is invalid
  Bytecode:
    0x0000000: b200 4601 a500 0ab2 004c 01a6 0006 a700
    0x0000010: 0ab2 004f 01a6 0006 a700 0db2 004f b400
    0x0000020: 5501 a600 06a7 0012 b200 4fb4 0055 b400
    0x0000030: 5bb2 0060 a500 06a7 0009 b800 669a 0006
    0x0000040: a700 0db2 006a 126c b900 7002 00b2 002e
    0x0000050: 2a2b 2cb6 0032 b1                      
  Stackmap Table:
    same_frame(@14)
    same_frame(@17)
    same_frame(@24)
    same_frame(@27)
    same_frame(@37)
    same_frame(@40)
    same_frame(@55)
    same_frame(@58)
    same_frame(@64)
    same_frame(@67)
    same_frame(@77)

	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.VerifyError: Illegal type at constant pool entry 102 in class forcekey.OverrideConnectionPatch
Exception Details:
  Location:
    forcekey/OverrideConnectionPatch.overrideConnection(Lcom/megacrit/cardcrawl/map/MapRoomNode;[Ljava/lang/Boolean;[Ljava/lang/Boolean;)V @58: invokestatic
  Reason:
    Constant pool index 102 is invalid
  Bytecode:
    0x0000000: b200 4601 a500 0ab2 004c 01a6 0006 a700
    0x0000010: 0ab2 004f 01a6 0006 a700 0db2 004f b400
    0x0000020: 5501 a600 06a7 0012 b200 4fb4 0055 b400
    0x0000030: 5bb2 0060 a500 06a7 0009 b800 669a 0006
    0x0000040: a700 0db2 006a 126c b900 7002 00b2 002e
    0x0000050: 2a2b 2cb6 0032 b1                      
  Stackmap Table:
    same_frame(@14)
    same_frame(@17)
    same_frame(@24)
    same_frame(@27)
    same_frame(@37)
    same_frame(@40)
    same_frame(@55)
    same_frame(@58)
    same_frame(@64)
    same_frame(@67)
    same_frame(@77)

	at com.megacrit.cardcrawl.map.MapRoomNode.update(MapRoomNode.java:277)
	at com.megacrit.cardcrawl.screens.DungeonMapScreen.update(DungeonMapScreen.java:100)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2561)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by 280chan** [comment]
I know what caused the bug, but I still don't know why, so I made a special case to avoid the crash

**Comment by 280chan** [comment]
I know what caused the bug, but I still don't know why, so I made a special case to avoid the crash

**Comment by 280chan** [comment]
I know what caused the bug, but I still don't know why, so I made a special case to avoid the crash
See: https://github.com/280chan/TestMod/blob/master/src/testmod/patches/PatchyPatchPatch.java
